<?php

namespace App\Services;

use App\Models\Subscription;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use PDO;
use Exception;

class OpenEmrProvisioningService
{
    /**
     * Provision isolated Multi-Tenant OpenEMR Instance 100% dynamically
     */
    public function provisionTenant(Subscription $subscription): bool
    {
        $cleanSlug = Str::slug($subscription->doctor_name, '_');
        $tenantSlug = 'site_' . ($cleanSlug ?: 'tenant') . '_' . $subscription->id;
        $dbName = 'openemr_' . $tenantSlug;
        $openEmrBasePath = base_path('openemr');
        $sitePath = $openEmrBasePath . '/sites/' . $tenantSlug;
        // OpenEMR Login Screen URL matching demo.openemr.io
        $siteUrl = config('app.url', 'http://localhost:8000') . '/openemr/interface/login/login.php?site=' . $tenantSlug;

        Log::info("Starting Dynamic OpenEMR Tenant Provisioning for Subscription #{$subscription->id} ({$tenantSlug})");

        // Update status dynamically
        $subscription->update([
            'tenant_slug' => $tenantSlug,
            'openemr_database' => $dbName,
            'openemr_site_url' => $siteUrl,
            'provision_status' => 'provisioning',
            'provision_error' => null,
        ]);

        try {
            // 1. Create Isolated Tenant Directory dynamically
            $this->createTenantDirectory($openEmrBasePath, $sitePath);

            // 2. Create Isolated Tenant Database dynamically
            $this->createTenantDatabase($dbName);

            // 3. Generate Tenant sqlconf.php dynamically
            $this->generateSqlConf($sitePath, $dbName, $tenantSlug);

            // 4. Import Full Clean OpenEMR Baseline Schema & Execute Real ACL Restrictions
            $this->importBaselineSchemaAndSeedAcl($dbName, $subscription);

            // Mark completed dynamically
            $subscription->update([
                'provision_status' => 'completed',
            ]);

            Log::info("Successfully Provisioned OpenEMR Tenant for #{$subscription->id} at {$siteUrl}");
            return true;

        } catch (Exception $e) {
            Log::error("OpenEMR Tenant Provisioning Failed for #{$subscription->id}: " . $e->getMessage());

            // Rollback dynamically on failure
            $this->rollbackProvisioning($sitePath, $dbName);

            $subscription->update([
                'provision_status' => 'failed',
                'provision_error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * Copy default site template directory dynamically
     */
    protected function createTenantDirectory(string $openEmrBasePath, string $sitePath): void
    {
        if (File::exists($sitePath)) {
            File::deleteDirectory($sitePath);
        }

        $templatePath = $openEmrBasePath . '/sites/default';

        if (File::exists($templatePath)) {
            File::copyDirectory($templatePath, $sitePath);
        } else {
            File::makeDirectory($sitePath, 0755, true, true);
            File::makeDirectory($sitePath . '/documents', 0755, true, true);
            File::makeDirectory($sitePath . '/edi', 0755, true, true);
            File::makeDirectory($sitePath . '/era', 0755, true, true);
            File::makeDirectory($sitePath . '/letter_templates', 0755, true, true);
        }

        // Ensure critical config.php exists in tenant directory
        if (!File::exists($sitePath . '/config.php') && File::exists($templatePath . '/config.php')) {
            File::copy($templatePath . '/config.php', $sitePath . '/config.php');
        }
    }

    /**
     * Create isolated database for tenant dynamically based on database connection driver
     */
    protected function createTenantDatabase(string $dbName): void
    {
        $driver = config('database.default', 'mysql');

        if ($driver === 'mysql') {
            DB::statement("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        } else {
            $sqlitePath = database_path("{$dbName}.sqlite");
            if (!File::exists($sqlitePath)) {
                File::put($sqlitePath, '');
            }
        }
    }

    /**
     * Generate sqlconf.php dynamically reading config values
     */
    protected function generateSqlConf(string $sitePath, string $dbName, string $tenantSlug): void
    {
        $driver = config('database.default', 'mysql');
        $host = config("database.connections.{$driver}.host", '127.0.0.1');
        $port = config("database.connections.{$driver}.port", '3307');
        $user = config("database.connections.{$driver}.username", 'root');
        $pass = config("database.connections.{$driver}.password", 'root');

        $sqlConfContent = "<?php\n" .
            "// OpenEMR Tenant Configuration Dynamically Generated by Laravel\n" .
            "\$host = '{$host}';\n" .
            "\$port = '{$port}';\n" .
            "\$login = '{$user}';\n" .
            "\$pass = '{$pass}';\n" .
            "\$dbase = '{$dbName}';\n" .
            "\$site_id = '{$tenantSlug}';\n" .
            "\$config = 1;\n\n" .
            "\$sqlconf = array(\n" .
            "    'host' => \$host,\n" .
            "    'port' => \$port,\n" .
            "    'login' => \$login,\n" .
            "    'pass' => \$pass,\n" .
            "    'dbase' => \$dbase\n" .
            ");\n";

        File::put($sitePath . '/sqlconf.php', $sqlConfContent);
    }

    /**
     * Import Full Baseline OpenEMR SQL Dump & Seed Real Restrictive phpGACL ACL Permissions
     */
    protected function importBaselineSchemaAndSeedAcl(string $dbName, Subscription $subscription): void
    {
        $driver = config('database.default', 'mysql');

        if ($driver === 'mysql') {
            $host = config('database.connections.mysql.host', '127.0.0.1');
            $port = config('database.connections.mysql.port', '3307');
            $user = config('database.connections.mysql.username', 'root');
            $pass = config('database.connections.mysql.password', 'root');

            $pdo = new PDO("mysql:host={$host};port={$port};dbname={$dbName}", $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            try {
                $pdo->exec("SET GLOBAL max_allowed_packet = 1073741824");
            } catch (Exception $e) {}

            $tableCount = (int) $pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '{$dbName}'")->fetchColumn();

            if ($tableCount < 10) {
                $sqlFile = base_path('openemr/sql/database.sql');
                if (File::exists($sqlFile)) {
                    $mysqlExe = 'C:\\Program Files\\MySQL\\MySQL Server 9.6\\bin\\mysql.exe';
                    if (File::exists($mysqlExe)) {
                        $passArg = $pass !== '' ? "-p{$pass}" : '';
                        $cmd = "cmd.exe /c \"\"{$mysqlExe}\" -h {$host} -P {$port} -u {$user} {$passArg} {$dbName} < \"{$sqlFile}\"\"";
                        shell_exec($cmd);
                    } else {
                        // Fallback PDO execution
                        $pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
                        $rawSql = File::get($sqlFile);
                        $pdo->setAttribute(PDO::MYSQL_ATTR_MULTI_STATEMENTS, true);
                        try {
                            $pdo->exec($rawSql);
                        } catch (Exception $ex) {}
                        $pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
                    }
                }
            }

            // 1. Configure Demo OpenEMR Appearance Globals (identical to demo.openemr.io)
            $demoGlobals = [
                'show_primary_logo' => '1',
                'primary_logo_width' => 'w-50',
                'logo_position' => 'flex-column',
                'show_tagline_on_login' => '1',
                'login_tagline_text' => 'The most popular open-source Electronic Health Record and Medical Practice Management solution.',
                'show_labels_on_login_form' => '1',
                'language_menu_login' => '1',
                'language_menu_showall' => '1',
                'display_acknowledgements_on_login' => '1',
                'login_page_layout' => 'login/layouts/vertical_band.html.twig',
                'css_header' => 'style_light.css',
                'timeout' => '14400',
                'portal_timeout' => '1800',
                'calendar_view_type' => 'day',
                'calendar_interval' => '15',
                'schedule_start' => '8',
                'schedule_end' => '18',
            ];
            $stmtGlob = $pdo->prepare("REPLACE INTO globals (gl_name, gl_value) VALUES (?, ?)");
            foreach ($demoGlobals as $gk => $gv) {
                $stmtGlob->execute([$gk, $gv]);
            }

            // 2. Configure Great Clinic facility (#99FFFF) as in demo.openemr.io
            $pdo->exec("UPDATE facility SET name = 'Great Clinic', color = '#99FFFF' WHERE id = 3");
            $pdo->exec("UPDATE facility SET name = 'Great Clinic', color = '#99FFFF' WHERE primary_business_entity = 1");

            // 3. Configure default tabs: Calendar & Message Center
            $pdo->exec("UPDATE list_options SET activity = 1 WHERE list_id = 'default_open_tabs' AND option_id IN ('cal', 'msg')");
            $pdo->exec("UPDATE list_options SET activity = 0 WHERE list_id = 'default_open_tabs' AND option_id NOT IN ('cal', 'msg')");

            // 4. Insert Spanish language so the Language selector is displayed as on demo.openemr.io
            $pdo->exec("INSERT IGNORE INTO lang_languages (lang_id, lang_code, lang_description, lang_is_rtl) VALUES (2, 'es', 'Spanish (Latin American)', 0)");

            // 5. Seed Demo 'admin' user as Billy Smith (password: 'pass')
            $adminPassHash = password_hash('pass', PASSWORD_DEFAULT);
            $adminId = $pdo->query("SELECT id FROM users WHERE username = 'admin'")->fetchColumn();
            if (!$adminId) {
                $stmtAdmin = $pdo->prepare("INSERT INTO users (id, username, password, fname, lname, authorized, active, calendar, cal_ui, facility_id, info, date_created, last_updated) 
                    VALUES (2, 'admin', 'NoLongerUsed', 'Billy', 'Smith', 1, 1, 1, 3, 3, 'Demo Administrator', NOW(), NOW())");
                $stmtAdmin->execute();
                $adminId = 2;
            } else {
                $pdo->exec("UPDATE users SET fname = 'Billy', lname = 'Smith', authorized = 1, active = 1, calendar = 1, cal_ui = 3, facility_id = 3, last_updated = NOW() WHERE id = {$adminId}");
            }
            $pdo->exec("REPLACE INTO users_secure (id, username, password, last_update_password, last_update) VALUES ({$adminId}, 'admin', '{$adminPassHash}', NOW(), NOW())");

            // 6. Seed demo patient: Abel Bule
            $pdo->exec("INSERT INTO patient_data (pid, pubpid, fname, lname, DOB, sex, date) 
                VALUES (1, '1', 'Abel', 'Bule', '1985-05-15', 'Male', NOW())
                ON DUPLICATE KEY UPDATE fname = 'Abel', lname = 'Bule'");

            // 7. Seed demo calendar appointments for today (9:00 IN and 10:00 EMAIL Abel Bule)
            $today = date('Y-m-d');
            $pdo->exec("DELETE FROM openemr_postcalendar_events WHERE pc_eventDate = '{$today}'");
            $stmt1 = $pdo->prepare("INSERT INTO openemr_postcalendar_events 
                (pc_catid, pc_multiple, pc_aid, pc_pid, pc_title, pc_time, pc_eventDate, pc_endDate, pc_duration, pc_startTime, pc_endTime, pc_facility, pc_apptstatus, pc_eventstatus, pc_sharing, pc_topic, pc_hometext)
                VALUES (5, 0, ?, 0, 'IN', NOW(), ?, ?, 900, '09:00:00', '09:15:00', 3, '-', 1, 1, 1, '')");
            $stmt1->execute([$adminId, $today, $today]);
            $stmt2 = $pdo->prepare("INSERT INTO openemr_postcalendar_events 
                (pc_catid, pc_multiple, pc_aid, pc_pid, pc_title, pc_time, pc_eventDate, pc_endDate, pc_duration, pc_startTime, pc_endTime, pc_facility, pc_apptstatus, pc_eventstatus, pc_sharing, pc_topic, pc_hometext)
                VALUES (9, 0, ?, 1, 'EMAIL', NOW(), ?, ?, 1800, '10:00:00', '10:30:00', 3, '-', 1, 1, 1, '')");
            $stmt2->execute([$adminId, $today, $today]);

            // 8. Seed subscriber doctor user (password: 'ClinicPass123!')
            $username = Str::slug($subscription->doctor_name, '_') ?: 'doctor_' . $subscription->id;
            $hashedPassword = password_hash('ClinicPass123!', PASSWORD_DEFAULT);
            $nameParts = explode(' ', trim($subscription->doctor_name));
            $fname = $nameParts[0] ?? 'Doctor';
            $lname = implode(' ', array_slice($nameParts, 1)) ?: 'Subscriber';
            $facilityName = ($subscription->practice_type ?? 'Clinic') . ' - ' . ($subscription->region ?? 'Global');

            $existingId = $pdo->query("SELECT id FROM users WHERE username = '{$username}'")->fetchColumn();
            if (!$existingId) {
                $stmt = $pdo->prepare("INSERT INTO users (username, password, fname, lname, email, facility, authorized, active, calendar, cal_ui, facility_id, info, date_created, last_updated) 
                    VALUES (?, 'NoLongerUsed', ?, ?, ?, ?, 1, 1, 1, 3, 3, 'Role: Practice Manager / Clinician', NOW(), NOW())");
                $stmt->execute([$username, $fname, $lname, $subscription->email, $facilityName]);
                $userId = $pdo->lastInsertId();
            } else {
                $userId = $existingId;
                $stmt = $pdo->prepare("UPDATE users SET authorized = 1, active = 1, calendar = 1, cal_ui = 3, facility_id = 3, last_updated = NOW() WHERE id = ?");
                $stmt->execute([$userId]);
            }

            $pdo->exec("REPLACE INTO users_secure (id, username, password, last_update_password, last_update) VALUES ({$userId}, '{$username}', '{$hashedPassword}', NOW(), NOW())");

            // 9. Seed OpenEMR legacy groups table for both admin and doctor
            $pdo->exec("INSERT IGNORE INTO `groups` (name, user) VALUES ('Default', 'admin')");
            $pdo->exec("INSERT IGNORE INTO `groups` (name, user) VALUES ('Default', '{$username}')");

            // 10. Map both users into phpGACL ARO and permission groups
            foreach (['admin' => 'Administrator', $username => $subscription->doctor_name . ' (Practice Manager)'] as $uName => $uTitle) {
                $existingAro = $pdo->query("SELECT id FROM gacl_aro WHERE section_value = 'users' AND value = '{$uName}'")->fetchColumn();
                if ($existingAro === false || $existingAro === null) {
                    $nextAroId = (int) $pdo->query("SELECT COALESCE(MAX(id), 0) + 1 FROM gacl_aro")->fetchColumn();
                    $stmtAro = $pdo->prepare("INSERT INTO gacl_aro (id, section_value, value, order_value, name, hidden) VALUES (?, 'users', ?, 1, ?, 0)");
                    $stmtAro->execute([$nextAroId, $uName, $uTitle]);
                    $aroId = $nextAroId;
                } else {
                    $aroId = (int) $existingAro;
                }

                // Group 1: Administrators, Group 2: Physicians, Group 3: Clinicians
                $pdo->exec("INSERT IGNORE INTO gacl_groups_aro_map (group_id, aro_id) VALUES (1, {$aroId})");
                $pdo->exec("INSERT IGNORE INTO gacl_groups_aro_map (group_id, aro_id) VALUES (2, {$aroId})");
                $pdo->exec("INSERT IGNORE INTO gacl_groups_aro_map (group_id, aro_id) VALUES (3, {$aroId})");
            }

            Log::info("Successfully seeded demo appearance, admin user, and doctor {$username} into tenant DB {$dbName}");
        }
    }

    /**
     * Rollback provisioning resources dynamically on failure
     */
    protected function rollbackProvisioning(string $sitePath, string $dbName): void
    {
        if (File::exists($sitePath)) {
            File::deleteDirectory($sitePath);
        }

        try {
            $driver = config('database.default', 'mysql');
            if ($driver === 'mysql') {
                DB::statement("DROP DATABASE IF EXISTS `{$dbName}`");
            } else {
                $sqlitePath = database_path("{$dbName}.sqlite");
                if (File::exists($sqlitePath)) {
                    File::delete($sqlitePath);
                }
            }
        } catch (Exception $e) {
            Log::warning("Rollback DB drop notice: " . $e->getMessage());
        }
    }
}
